# Generated by Django 5.0.6 on 2024-06-03 07:14

import core.feilds
import django.core.validators
from decimal import Decimal
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversionrate',
            name='conversion_rate',
            field=core.feilds.MoneyField(decimal_places=8, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='conversionrate',
            name='reverse_rate',
            field=core.feilds.MoneyField(decimal_places=8, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
