# Generated by Django 5.0.6 on 2024-06-03 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_conversionrate_conversion_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iswiftaccount',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
