# Generated by Django 5.0.6 on 2024-06-03 17:30

import core.feilds
import django.core.validators
import django.db.models.deletion
import django_extensions.db.fields
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_iswiftaccount_is_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.CharField(max_length=500)),
                ('amount_sent', core.feilds.MoneyField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('iswift_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debit_transactions', to='finance.iswiftaccount')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.CharField(max_length=500)),
                ('amount_received', core.feilds.MoneyField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('amount_sent', core.feilds.MoneyField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency_received', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_received', to='finance.currency')),
                ('currency_sent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='currency_sent', to='finance.currency')),
                ('iswift_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_transactions', to='finance.iswiftaccount')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('debit_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='finance.debittransaction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TransactionActivity',
        ),
    ]
