# Generated by Django 5.0.6 on 2024-05-31 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_country_code_user_first_name_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_verified_email',
            field=models.BooleanField(default=False),
        ),
    ]
